# Generated by Django 4.1.4 on 2023-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='checkbox',
            field=models.BooleanField(verbose_name='Отложенная отправка'),
        ),
    ]
